beatrice/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from registration.backends.simple.views import RegistrationView
from paranoia.forms import RegistrationExtendedForm

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', RedirectView.as_view(url='/p')),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/accounts/login'}),

    url(r'accounts/register/$',
        RegistrationView.as_view(form_class = RegistrationExtendedForm),
        name = 'registration_register'),

    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/profile/$', RedirectView.as_view(url='/p/profile')),
    url(r'^users/', RedirectView.as_view(url='/p')),

    url(r'^p/', include('paranoia.urls', namespace="paranoia")),
    url(r'^p/admin/', include('paranoia_admin.urls', namespace="paranoia_admin")),

    url(r'^p-admin/alliances/', include('p_alliances.urls', namespace="p_alliances")),
    url(r'^p-admin/fractions/', include('p_fractions.urls', namespace="p_fractions")),
    url(r'^p-admin/points/', include('p_points.urls', namespace="p_points")),


    url(r'^admin/', include(admin.site.urls)),
)

p_fractions/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView

from p_fractions import views


urlpatterns = patterns('',

    url(r'^list', views.fractions_list, name='fractions_list'),
    url(r'^add-update/((?P<id>\d+))?$', views.fractions_details, name='fractions_details'),
    url(r'^delete$', views.fraction_delete, name='fractions_delete'),
)

p_fractions/models.py
from django.db import models
from p_alliances.models import Alliance


class Fraction(models.Model):
    name = models.CharField(max_length=200)
    game_name = models.CharField(max_length=200)
    color = models.CharField(max_length=200)
    alliance = models.ForeignKey(Alliance, unique=True)

    def __unicode__(self):
        return self.name

p_fractions/forms.py
from django import forms
from p_fractions.models import Fraction


class FractionForm(forms.ModelForm):

  class Meta:
    model = Fraction

p_fractions/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.core.urlresolvers import reverse

from p_fractions.forms import FractionForm
from p_fractions.models import Fraction


@login_required
@require_http_methods(["GET"])
def fractions_list(request):
    items = Fraction.objects.all()
    context = {'items': items}
    return render(request, 'f_list.html', context)


@login_required
@require_http_methods(["GET", "POST"])
def fractions_details(request, id=None):
    update_mode = False or (id is not None)
    context = {}
    if request.method == 'POST':
        new_fraction = None
        if update_mode:
            fraction = Fraction.objects.get(pk=id)
            fraction_form = FractionForm(request.POST, instance=fraction)
            if fraction_form.is_valid():
                new_fraction = fraction_form.save(commit=False)
                new_fraction.save()
        else:
            " handle creation of new objects "
            form = FractionForm(request.POST)
            if form.is_valid():
                new_fraction = form.save()
            else:
                return render(request, 'f_details.html', {'formset': [form]})

        if new_fraction is not None:
            return HttpResponseRedirect(reverse('p_fractions:fractions_list'))

    # GET
    else:
        if id is not None:
            " request for an edit form "
            fraction = Fraction.objects.get(id=id)
            fraction_form = FractionForm(instance=fraction)
            context['fraction_id'] = fraction.id
            context['formset'] = [fraction_form]
        else:
            " request for create form. Return empty "
            fraction_form = FractionForm()
            context['formset'] = [fraction_form]

    return render(request, 'f_details.html', context)


@login_required
@require_http_methods(["POST"])
def fraction_delete(request):
    Fraction.objects.filter(id=request.POST['id']).delete()
    return HttpResponse(json.dumps({'is_success':True }), content_type="application/json")

p_fractions/templates/f_details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block content %}
<div class="page-header">
    <h2>Fraction Details</h2>
</div>

<form class="form-horizontal" role="form" action="{% url 'p_fractions:fractions_details' fraction_id %}" method="POST">
    {% csrf_token %}


    {{ form.management_form }}
    {% for form in formset %}
    {% for field in form.visible_fields %}

    <div class="form-group {%if field.errors %}has-error{%endif%}">
        <label class="col-sm-2 control-label">{{ field.label_tag }} </label>
        <div class="col-sm-4">
            {{ field|add_class:"form-control" }}
        </div>
        {% if field.errors %}
        <span class="help-block text-danger">{{ field.errors }}</span>
        {% endif %}
    </div>

    {% endfor %}

    {% for field in form.hidden_fields %}
    <div style="display:none;">{{ field }}</div>
    {% endfor %}
    {% endfor %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>
</form>



{% endblock %}

p_fractions/templates/f_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block content %}
<div class="page-header">
    <h2>Fractions List</h2>
</div>

{% csrf_token %}
<a href="{% url 'p_fractions:fractions_details' %}">Add</a>

<table class="table table-hover">
    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Game Name</th>
        <th>Alliance Name</th>
        <th></th>
    </tr>
    </thead>
    <tbody>

    {% for fraction in items %}
    <tr data-id="{{ fraction.id }}">
        <td>
            {{ forloop.counter }}
        </td>
        <td>
            {{ fraction.name }}
        </td>
        <td>
            {{ fraction.game_name }}
        </td>
        <td>
            {{ fraction.alliance.name }}
        </td>
        <td>
            <a href="{% url 'p_fractions:fractions_details' fraction.id %}">View</a>
            <a href="javascript:void(0)" class="delete-item">Delete</a>
        </td>
    </tr>
    {% endfor %}

    </tbody>
</table>

{% endblock %}

{% block pagescripts %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=drawing&language=en">
</script>

<script src="{% static 'app/fractions/fraction_list.js' %}" type="text/javascript"></script>
<script type="text/javascript">
  $(document).ready(function(){
    var settings = {
      urlDelete: "{% url 'p_fractions:fractions_delete' %}"
    };
    var model = new FractionList(settings);
    model.initPage();
  });

</script>
{% endblock %}