beatrice/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from registration.backends.simple.views import RegistrationView
from paranoia.forms import RegistrationExtendedForm

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', RedirectView.as_view(url='/p')),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/accounts/login'}),

    url(r'accounts/register/$',
        RegistrationView.as_view(form_class = RegistrationExtendedForm),
        name = 'registration_register'),

    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/profile/$', RedirectView.as_view(url='/p/profile')),
    url(r'^users/', RedirectView.as_view(url='/p')),

    url(r'^p/', include('paranoia.urls', namespace="paranoia")),
    url(r'^p/admin/', include('paranoia_admin.urls', namespace="paranoia_admin")),

    url(r'^p-admin/alliances/', include('p_alliances.urls', namespace="p_alliances")),
    url(r'^p-admin/fractions/', include('p_fractions.urls', namespace="p_fractions")),
    url(r'^p-admin/points/', include('p_points.urls', namespace="p_points")),


    url(r'^admin/', include(admin.site.urls)),
)

p_alliances/urls.py
from django.conf.urls import patterns, include, url
from p_alliances import views


urlpatterns = patterns('',

    url(r'^list', views.alliances_list, name='alliances_list'),
    url(r'^add-update/((?P<id>\d+))?$', views.addUpdateAlliance, name='addUpdateAlliance'),
    url(r'^delete$', views.alliance_delete, name='alliance_delete'),
)

p_alliances/models.py
from django.db import models


class Alliance(models.Model):
    name = models.CharField(max_length=200)
    game_name = models.CharField(max_length=200)
    color = models.CharField(max_length=200)

    def __unicode__(self):
        return self.name

p_alliances/forms.py
from django import forms
from p_alliances.models import Alliance


class AllianceForm(forms.ModelForm):

  class Meta:
    model = Alliance

p_alliances/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.core.urlresolvers import reverse
import json
from django.views.decorators.http import require_http_methods
from p_alliances.forms import AllianceForm
from p_alliances.models import Alliance


@login_required
@require_http_methods(["GET"])
def alliances_list(request):
  items = Alliance.objects.all()
  context = { 'items':items }
  return render(request, 'list.html', context)


@login_required
@require_http_methods(["GET", "POST"])
def addUpdateAlliance(request, id=None):

  update_mode = False or (id is not None)
  context = {}
  if request.method == 'POST':
    new_alliance = None
    if update_mode:
      alliance = Alliance.objects.get(pk=id)
      aForm = AllianceForm(request.POST, instance=alliance)
      if aForm.is_valid():
        new_alliance = aForm.save(commit=False)
        new_alliance.save()
    else:
      " handle creation of new objects "
      form = AllianceForm({'name': request.POST['name'],
                        'game_name': request.POST['game_name'],
                        'color':request.POST['color']})
      if form.is_valid():
        new_alliance = form.save()
      else:
        return render(request, 'addUpdate.html', {'formset':[form]})


    if new_alliance is not None:
      return HttpResponseRedirect(reverse('p_alliances:alliances_list'))

  # GET
  else:
    if id is not None:
      " request for an edit form "
      alliance = Alliance.objects.get(id=id)
      aForm = AllianceForm(instance=alliance)
      context['alliance_id'] = alliance.id
      context['formset'] = [aForm]
    else:
      " request for create form. Return empty "
      allianceForm = AllianceForm()
      context['formset'] = [allianceForm]

  return render(request, 'addUpdate.html', context)


@login_required
@require_http_methods(["POST"])
def alliance_delete(request):
    Alliance.objects.filter(id=request.POST['id']).delete()
    return HttpResponse(json.dumps({'is_success':True }), content_type="application/json")

p_alliances/templates/addUpdate.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block content %}
<div class="page-header">
    <h2>Alliance details</h2>
</div>

<form class="form-horizontal" role="form" action="{% url 'p_alliances:addUpdateAlliance' alliance_id %}" method="POST">
    {% csrf_token %}


    {{ form.management_form }}
    {% for form in formset %}
    {% for field in form.visible_fields %}

    <div class="form-group {%if field.errors %}has-error{%endif%}">
        <label class="col-sm-2 control-label">{{ field.label_tag }} </label>
        <div class="col-sm-4">
            {{ field|add_class:"form-control" }}
        </div>
        {% if field.errors %}
        <span class="help-block text-danger">{{ field.errors }}</span>
        {% endif %}
    </div>

    {% endfor %}

    {% for field in form.hidden_fields %}
    <div style="display:none;">{{ field }}</div>
    {% endfor %}
    {% endfor %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Save</button>
        </div>
    </div>
</form>



{% endblock %}

p_alliances/templates/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block content %}
<div class="page-header">
    <h2>Alliances List</h2>
</div>

{% csrf_token %}
<a href="{% url 'p_alliances:addUpdateAlliance' %}">Add</a>

<table class="table table-hover" id="alliancesListTable">
    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Game Name</th>
        <th></th>
    </tr>
    </thead>
    <tbody>

    {% for alliance in items %}
    <tr data-id="{{ alliance.id }}">
        <td>
            {{ forloop.counter }}
        </td>
        <td>
            {{ alliance.name }}
        </td>
        <td>
            {{ alliance.game_name }}
        </td>
        <td>
            <a href="{% url 'p_alliances:addUpdateAlliance' alliance.id %}">View</a>
            <a href="javascript:void(0)" class="delete-item">Delete</a>
        </td>
    </tr>
    {% endfor %}

    </tbody>
</table>

{% endblock %}


{% block pagescripts %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=drawing&language=en">
</script>

<script src="{% static 'app/paranoia_admin/alliance_list.js' %}" type="text/javascript"></script>
<script type="text/javascript">
  $(document).ready(function(){
    var settings = {
      urlDelete: "{% url 'p_alliances:alliance_delete' %}"
    };
    var model = new AllianceList(settings);
    model.initPage();
  });


</script>
{% endblock %}