beatrice/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from registration.backends.simple.views import RegistrationView
from paranoia.forms import RegistrationExtendedForm

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', RedirectView.as_view(url='/p')),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/accounts/login'}),

    url(r'accounts/register/$',
        RegistrationView.as_view(form_class = RegistrationExtendedForm),
        name = 'registration_register'),

    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/profile/$', RedirectView.as_view(url='/p/profile')),
    url(r'^users/', RedirectView.as_view(url='/p')),

    url(r'^p/', include('paranoia.urls', namespace="paranoia")),
    url(r'^p/admin/', include('paranoia_admin.urls', namespace="paranoia_admin")),

    url(r'^p-admin/alliances/', include('p_alliances.urls', namespace="p_alliances")),
    url(r'^p-admin/fractions/', include('p_fractions.urls', namespace="p_fractions")),
    url(r'^p-admin/points/', include('p_points.urls', namespace="p_points")),


    url(r'^admin/', include(admin.site.urls)),
)

p_alliances/urls.py
from django.conf.urls import patterns, include, url
from p_alliances import views


urlpatterns = patterns('',

    url(r'^list', views.alliances_list, name='alliances_list'),
    url(r'^add-update/((?P<id>\d+))?$', views.addUpdateAlliance, name='addUpdateAlliance'),
    url(r'^delete$', views.alliance_delete, name='alliance_delete'),
)

p_fractions/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView

from p_fractions import views


urlpatterns = patterns('',

    url(r'^list', views.fractions_list, name='fractions_list'),
    url(r'^add-update/((?P<id>\d+))?$', views.fractions_details, name='fractions_details'),
    url(r'^delete$', views.fraction_delete, name='fractions_delete'),
)

p_points/urls.py
from django.conf.urls import patterns, url
from p_points import views


urlpatterns = patterns('',


    url(r'keys/get-form/$', views.get_key_points_form, name='get_key_points_form'),
    url(r'keys/get-list-form/$', views.get_key_points_list_form, name='get_key_points_list_form'),

    url(r'keys/add-or-update/$', views.add_or_update_point, name='add_or_update_point'),
    url(r'^keys/', views.key_points, name='key_points'),

    url(r'^quests', views.quest_points, name='quest_points')
)

paranoia_admin/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView

from paranoia_admin import views


urlpatterns = patterns('',

    url(r'^players-list', views.players_list, name='players_list'),
    url(r'^players-details', views.players_details, name='players_details'),

)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'dist/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'datepicker/css/datepicker.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sticky-footer-navbar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'select2-3.4.6/select2.css' %}">

    <script src="{% static 'jquery-1.11.0.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'datatables-1.9.4.js' %}" type="text/javascript"></script>
    <script src="{% static 'dist/js/bootstrap.js' %}" type="text/javascript"></script>
    <script src="{% static 'dist/js/bootstrap-carousel.js' %}" type="text/javascript"></script>
    <script src="{% static 'select2-3.4.6/select2.js' %}" type="text/javascript"></script>
    <script src="{% static 'datepicker/js/bootstrap-datepicker.js' %}" type="text/javascript" />
    <script src="{% static 'knockout-3.1.0.js' %}" type="text/javascript"></script>
    <script src="{% static 'require.js' %}" type="text/javascript"></script>
    <script src="{% static 'main.js' %}" type="text/javascript"></script>

    <script src="{% static 'app/utils.js' %}" type="text/javascript"></script>

    <script data-main="{% static 'main.js' %}" src="{% static 'require.js' %}"></script>
    <title>{% block title %}Paranoia{% endblock %}</title>
</head>


<body>
<div class="navbar navbar-inverse navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Paranoia</a>
        </div>

        {% if user.is_superuser %}

        <ul class="nav navbar-nav">

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li class="dropdown-header">groups</li>
                    <li><a href="{% url 'p_alliances:alliances_list' %}">Alliances</a></li>
                    <li><a href="{% url 'p_fractions:fractions_list' %}">Fractions</a></li>
                    <li class="divider"></li>
                    <li class="dropdown-header">points</li>
                    <li><a href="{% url 'p_points:key_points' %}">Keys Points</a></li>
                    <li><a href="{% url 'p_points:quest_points' %}">Quests Points</a></li>
                </ul>
            </li>
            <li>
                <a href="{% url 'paranoia_admin:players_list' %}">Players</a>
            </li>
        </ul>

        {% endif %}

        <div class="navbar-collapse collapse">
            {% if user.is_authenticated %}
            <div class="navbar-header navbar-right">
                <a class="navbar-brand" href="{% url 'auth_logout' %}">Logout</a>
            </div>
            <div class="navbar-header navbar-right">
                <a class="navbar-brand" href="#">Hello, {{ user.username }}</a>
            </div>
            {% else %}

            <div class="form-group">
                <div class="navbar-header navbar-right">
                    <a class="navbar-brand" href="{% url 'auth_login' %}">Login</a>
                </div>
                <div class="navbar-header navbar-right">
                    <a class="navbar-brand" href="{% url 'registration_register' %}">Register</a>
                </div>
            </div>

            {% endif %}
        </div>
    </div>
</div>

<div class="container" id="content">
    {% block content %}{% endblock %}
</div>

{% block pagescripts %}{% endblock %}
<div id="footer">
    <div class="container">
        <p class="text-muted">{% now "Y" %} Grey Order.</p>
    </div>
</div>
</body>
</html>