beatrice/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
from registration.backends.simple.views import RegistrationView
from paranoia.forms import RegistrationExtendedForm

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', RedirectView.as_view(url='/p')),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/accounts/login'}),

    url(r'accounts/register/$',
        RegistrationView.as_view(form_class = RegistrationExtendedForm),
        name = 'registration_register'),

    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^accounts/profile/$', RedirectView.as_view(url='/p/profile')),
    url(r'^users/', RedirectView.as_view(url='/p')),

    url(r'^p/', include('paranoia.urls', namespace="paranoia")),
    url(r'^p/admin/', include('paranoia_admin.urls', namespace="paranoia_admin")),

    url(r'^p-admin/alliances/', include('p_alliances.urls', namespace="p_alliances")),
    url(r'^p-admin/fractions/', include('p_fractions.urls', namespace="p_fractions")),
    url(r'^p-admin/points/', include('p_points.urls', namespace="p_points")),


    url(r'^admin/', include(admin.site.urls)),
)

p_points/urls.py
from django.conf.urls import patterns, url
from p_points import views


urlpatterns = patterns('',


    url(r'keys/get-form/$', views.get_key_points_form, name='get_key_points_form'),
    url(r'keys/get-list-form/$', views.get_key_points_list_form, name='get_key_points_list_form'),

    url(r'keys/add-or-update/$', views.add_or_update_point, name='add_or_update_point'),
    url(r'^keys/', views.key_points, name='key_points'),

    url(r'^quests', views.quest_points, name='quest_points')
)

p_points/models.py
from django.utils import timezone
from django.db import models

from p_alliances.models import Alliance
from p_fractions.models import Fraction
from paranoia.models import UserProfile


class Point(models.Model):
    title = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now=True)
    date_updated = models.DateTimeField(auto_now=True)
    lat = models.FloatField()
    lon = models.FloatField()

    class Meta:
        abstract = True

    def __unicode__(self):
        return self.name


class KeyPoint(Point):
    fraction = models.ForeignKey(Fraction, related_name='keypoint_fraction')
    is_secret = models.BooleanField(default=False)
    income_personal = models.DecimalField(max_digits=5, decimal_places=2)
    income_fraction = models.DecimalField(max_digits=5, decimal_places=2)
    ctrl_fraction = models.ForeignKey(Fraction, related_name='keypoint_ctrl_fraction')
    owner = models.ForeignKey(UserProfile)
    distance_capture = models.FloatField()
    distance_open = models.FloatField()
    is_refresh = models.BooleanField(default=False)
    date_refresh = models.DateTimeField()


class QuestPoint(Point):
    walkthrough_limit = models.IntegerField(default=1)
    walkthrough_rest = models.IntegerField(default=1)
    loyalty = models.IntegerField()
    fraction = models.ForeignKey(Fraction)
    alliance = models.ForeignKey(Alliance)
    distance_take = models.FloatField()
    predecessor = models.ForeignKey('self')
    date_activated = models.DateTimeField()
    date_expiration = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    description_short = models.TextField()
    description_taking = models.TextField()

p_points/forms.py
from django import forms
from p_points.models import KeyPoint, QuestPoint


class KeyPointForm(forms.ModelForm):
    class Meta:
        model = KeyPoint


class QuestPointForm(forms.ModelForm):
    class Meta:
        model = QuestPoint

p_points/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.template.loader import render_to_string
from django.utils import timezone
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.http import require_http_methods
from django.views.generic import CreateView, DetailView
from p_points.forms import KeyPointForm
from p_points.models import KeyPoint
import json


@login_required
@require_http_methods(["GET"])
def key_points(request):
    context = {}
    if request.is_ajax():
        key_point_form = KeyPointForm()
        context['formset'] = [key_point_form]
        template = 'key_form_partial.html'
    else:
        template = 'key_points.html'
    return render(request, template, context)


def get_key_points_form(request):
    context = {}
    key_point_form = KeyPointForm()
    context['formset'] = [key_point_form]
    return render_to_response('key_form_partial.html', context, context_instance=RequestContext(request))



def get_key_points_list_form(request):
    context = {'items': KeyPoint.objects.all()}
    return render_to_response('key_marker_list_partial.html', context, context_instance=RequestContext(request))


@require_http_methods(["POST"])
def add_or_update_point(request):
    context = {'is_success': True, 'message': 'Point has been added.'}
    form = KeyPointForm(request.POST)
    if form.is_valid():
        new_point = form.save()
        return HttpResponse(json.dumps(context), content_type="application/json")
    else:
        context['message'] = 'Point hasn\'t been added. Form is invalid.'
        context['errors'] = form.errors
        return HttpResponse(json.dumps(context), content_type="application/json")



@login_required
@require_http_methods(["GET"])
def quest_points(request):
    items = {}
    context = {'items': items}
    return render(request, 'quest_points.html', context)

p_points/templates/key_form_partial.html
{% load staticfiles %}
{% load widget_tweaks %}

<hr/>
<form class="form-horizontal" role="form" id="KeyPointForm">
    {% csrf_token %}

    {% for form in formset %}

    <div class="form-group">
        <label class="col-sm-2 control-label">Title</label>

        <div class="col-sm-4">
            {{ form.title|add_class:"form-control"|attr:"tabindex:1" }}
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Latitude</label>

        <div class="col-sm-4">
            {{ form.lat|add_class:"form-control"|attr:"tabindex:2" }}
        </div>
        <label class="col-sm-2 control-label">Longitude</label>

        <div class="col-sm-4">
            {{ form.lon|add_class:"form-control"|attr:"tabindex:8" }}
        </div>

    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Fraction</label>

        <div class="col-sm-4">
            {{ form.fraction|add_class:"form-control select2"|attr:"tabindex:3" }}
        </div>
        <div class=" col-sm-offset-2 col-sm-4">
            <div class="checkbox">
                <label>
                    {{ form.is_secret|attr:"tabindex:9" }} Is secret
                </label>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Income Personal</label>

        <div class="col-sm-4">
            {{ form.income_personal|add_class:"form-control"|attr:"tabindex:4" }}
        </div>

        <div class=" col-sm-offset-2 col-sm-4">
            <div class="checkbox">
                <label>
                    {{ form.is_refresh|attr:"tabindex:10" }} Is refresh
                </label>
            </div>
        </div>

    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Income Fraction</label>

        <div class="col-sm-4">
            {{ form.income_fraction|add_class:"form-control"|attr:"tabindex:5" }}
        </div>

        <label class="col-sm-2 control-label">Date Refresh</label>

        <div class="col-sm-4">
            {{ form.date_refresh|add_class:"form-control date-picker"|attr:"tabindex:11" }}
        </div>


    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Control Fraction</label>

        <div class="col-sm-4">
            {{ form.ctrl_fraction|add_class:"form-control select2"|attr:"tabindex:6" }}
        </div>

        <label class="col-sm-2 control-label">Distance Capture</label>

        <div class="col-sm-4">
            {{ form.distance_capture|add_class:"form-control"|attr:"tabindex:12" }}
        </div>
    </div>

    <div class="form-group">
        <label class="col-sm-2 control-label">Owner</label>

        <div class="col-sm-4">
            {{ form.owner|add_class:"form-control select2"|attr:"tabindex:7" }}
        </div>

        <label class="col-sm-2 control-label">Distance Open</label>

        <div class="col-sm-4">
            {{ form.distance_open|add_class:"form-control"|attr:"tabindex:13" }}
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="button" class="btn btn-default" id="SaveBtn" tabindex="14">Create</button>
        </div>
    </div>

    {% for field in form.hidden_fields %}
    <div style="display:none;">{{ field }}</div>
    {% endfor %}
    {% endfor %}
</form>

p_points/templates/key_marker_list_partial.html
{% load staticfiles %}
{% load widget_tweaks %}

<div class="list-group list-added-markers" id="KeyListForm">
    {% for item in items %}

    <a href="javascript:void(0)" class="list-group-item point-item">{{ item.title }}</a>

    {% endfor %}
</div>

p_points/templates/key_points.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/admin.css' %}">
<form id="TestForm" target="_blank" action="www.google.com">
    <input type="button" value="CLICK" id="TestButton" />
</form>
<div class="page-header">
    <h2>Map</h2>
</div>

<div class="panel panel-default">
    <div class="panel-heading">Settings</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-2">
                <input id="tbLatitude" class="form-control w50p" type="text" placeholder="Latitude"
                       data-bind="value: firstName" value="53.89">
            </div>
            <div class="col-sm-2">
                <input id="tbLongitude" class="form-control w50p" type="text" placeholder="Longitude"
                       data-bind="value: lastName" value="27.56666700000026">
            </div>
            <div class="col-sm-2">
                <input type="button" class="btn btn-success" id="AddKeyPoint" value="Add"/>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <div id="MapContainer" class="well">
        </div>
    </div>
    <div class="col-md-4 well" style="overflow-y: scroll; height:400px;">
        <div class="list-group list-added-markers" id="KeyListForm">
        </div>
    </div>
</div>

<form id="KeyPointForm">
    {% csrf_token %}
</form>
{% endblock %}



{% block pagescripts %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=drawing&language=en">
</script>

<script src="{% static 'app/points/key_points.js' %}" type="text/javascript"></script>
<script src="{% static 'app/maputils.js' %}" type="text/javascript"></script>
<script type="text/javascript">
  $(document).ready(function(){

   $('#TestButton').click(function(){
        var form = $('#TestButton').closest('form');
        form.submit();
   });

    var settings = {
      urlForm: "{% url 'p_points:key_points' %}",
      urlListForm: "{% url 'p_points:get_key_points_list_form' %}",
      urlAddOrUpdate: "{% url 'p_points:add_or_update_point' %}",
    };
    var model = new KeyPoints(settings);
    model.initPage();
  });





</script>
{% endblock %}

p_points/templates/quest_points.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/admin.css' %}">

<div class="page-header">
    <h2>Quest Points</h2>
</div>

<div class="panel panel-default">
    <div class="panel-heading">Settings</div>
    <div class="panel-body">
        <div class="col-sm-4 input-group">
            <input id="tbLatitude" class="form-control w50p" type="text" placeholder="Latitude"
                   data-bind="value: firstName" value="53.89">
            <input id="tbLongitude" class="form-control w50p" type="text" placeholder="Longitude"
                   data-bind="value: lastName" value="27.56666700000026">
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8">
        <div id="MapContainer" class="well">

        </div>
    </div>
    <div class="col-md-4 well" style="overflow-y: scroll; height:400px;">
        <div class="list-group list-added-markers">
        </div>
    </div>
</div>

{% endblock %}

{% block pagescripts %}
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=drawing&language=en">
</script>

<script src="{% static 'app/points/quest_points.js' %}" type="text/javascript"></script>
<script src="{% static 'app/maputils.js' %}" type="text/javascript"></script>
<script type="text/javascript">
  $(document).ready(function(){
    var settings = {

    };
    var model = new QuestPoints(settings);
    model.initPage();
  });
</script>
{% endblock %}